# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Oskar Murand
paginate:       5
baseurl:        "/"
url:            "https://oskarmurand.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Oskar Murand
  url:          http://oskarmurand.github.io
  email:        oskar.murand@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/oskarmurand/oskarmurand.github.io

# Gems
plugins:
  - jekyll-paginate
